/*
 * This source file was generated by the Gradle 'init' task
 */
package ch.bbcag.benjamin.Factorylibs;

import ch.bbcag.benjamin.Factorylibs.world.main.HandleInput;
import ch.bbcag.benjamin.Factorylibs.world.main.World;
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;

public class MyGame extends ApplicationAdapter {
    private SpriteBatch batch;
    private World world;

    @Override
    public void create() {
        batch = new SpriteBatch();
        world = new World(batch);
        Gdx.input.setInputProcessor(new HandleInput());
    }

    @Override
    public void render() {
        HandleInput.handlePollingInput(world);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        batch.begin();
        world.draw();
        batch.end();
    }

    @Override
    public void dispose() {
        batch.dispose();
        world.dispose();
    }
}

