/*
 * This source file was generated by the Gradle 'init' task
 */
package ch.bbcag.benjamin.Factorylibs;

import ch.bbcag.benjamin.Factorylibs.world.main.World;
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Input;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;

public class MyGame extends ApplicationAdapter {
    private SpriteBatch batch;
    private World world;
    public static final int CAMERASPEED = 16;

    @Override
    public void create() {
        batch = new SpriteBatch();
        world = new World(batch);
    }

    @Override
    public void render() {
        if (Gdx.input.isKeyPressed(Input.Keys.W)) {
            world.getMainCamera().moveUp(CAMERASPEED);
        }
        if (Gdx.input.isKeyPressed(Input.Keys.S)) {
            world.getMainCamera().moveDown(CAMERASPEED);
        }
        if (Gdx.input.isKeyPressed(Input.Keys.A)) {
            world.getMainCamera().moveLeft(CAMERASPEED);
        }
        if (Gdx.input.isKeyPressed(Input.Keys.D)) {
            world.getMainCamera().moveRight(CAMERASPEED);
        }

        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        batch.begin();
        world.draw();
        batch.end();
    }

    @Override
    public void dispose() {
        batch.dispose();
        world.dispose();
    }
}

